-- ============================================================================
-- PIIP MIDAGRI - Carga manual: documento de aprobacion PEI
-- Archivo: 022_documento_aprobacion_pei.sql
-- Esquema: KALLPA_PIIP
-- Modulo: documentos
-- Dependencias: 003+003.1+003.2 VIGENTES
-- Compensacion: conservar expediente, serie y documento cargados.
-- ============================================================================
SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

-- Expediente institucional
INSERT INTO EXPEDIENTE_INSTITUCIONAL (ID_EXPEDIENTE, CODIGO, ASUNTO, MODULO_ORIGEN, REFERENCIA_CASO_USO, ID_UNIDAD, CLASIFICACION, ACTIVO, VERSION, CREADO_POR, FECHA_CREACION)
VALUES (SEQ_EXPEDIENTE_INSTITUCIONAL.NEXTVAL, 'EXP-PEI-001', 'Aprobacion PEI', 'ORGANIZACION', 'APROBACION_PEI', 1, 'INTERNO', 'S', 0, 'CARGA_MANUAL_022', SYSTIMESTAMP);

-- Serie documental
INSERT INTO DOCUMENTO_SERIE (ID_SERIE, ID_TIPO_DOC, ID_EXPEDIENTE, TITULO, CLASIFICACION_PROPUESTA, ACTIVA, VERSION, CREADO_POR, FECHA_CREACION)
VALUES (SEQ_DOCUMENTO_SERIE.NEXTVAL, 48, SEQ_EXPEDIENTE_INSTITUCIONAL.CURRVAL, 'Aprobacion PEI', 'INTERNO', 'S', 0, 'CARGA_MANUAL_022', SYSTIMESTAMP);

-- Documento
INSERT INTO DOCUMENTO (ID_DOCUMENTO, ID_PROYECTO, ID_TIPO_DOC, ESTADO_AL_CARGAR, NOMBRE_ORIGINAL, NOMBRE_STORAGE, MIME_TYPE, TAMANO_BYTES, HASH_SHA256, ID_USUARIO_CARGA, FECHA_CARGA, ACTIVO, INMUTABLE, SCAN_ANTIVIRUS, NUMERO_VERSION, ID_DOCUMENTO_SERIE, CLASIFICACION)
VALUES (SEQ_DOCUMENTO.NEXTVAL, NULL, 48, 'PROYECTO_EJECUCION', 'test_documento_aprobacion_poi.jpg', 'test_documento_aprobacion_poi', 'image/jpeg', 1000, '8ad420862605b92d170aec4162b1ebe6cd277657368d543000e0ddfd26d16a53', 8, SYSTIMESTAMP, 'S', 'S', 'PENDIENTE', 1, SEQ_DOCUMENTO_SERIE.CURRVAL, 'INTERNO');

COMMIT;
PROMPT Carga manual 022 completada correctamente.