-- ============================================================================
-- PIIP MIDAGRI - Pruebas manuales 008/008.1: vigencia y aprovisionamiento
-- Dependencia: 001, 002, 003, 003.1, 003.2, 007, 008 parcial y 008.1 VIGENTES.
-- Proposito : verifica secuencias 008.1, vigencia, revocacion, suplencia y
--             operacion recuperable. Limpieza por ROLLBACK TO; secuencias no
--             revierten sus valores en Oracle.
-- Nota: UK_URU_USR_ROL_UNI heredada sigue vigente; no se prueba historial
--       repetido con la misma terna hasta una correccion fisica aprobada.
-- ============================================================================

SET DEFINE OFF
SET VERIFY OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SAVEPOINT T008_VIGENCIA;

DECLARE
    v_u1 NUMBER(10) := SEQ_USUARIO.NEXTVAL;
    v_u2 NUMBER(10) := SEQ_USUARIO.NEXTVAL;
    v_exp NUMBER(12) := SEQ_EXPEDIENTE_INSTITUCIONAL.NEXTVAL;
    v_serie NUMBER(12) := SEQ_DOCUMENTO_SERIE.NEXTVAL;
    v_doc NUMBER(12) := SEQ_DOCUMENTO.NEXTVAL;
    v_mv NUMBER(10) := SEQ_MATRIZ_VERSION.NEXTVAL;
    v_fun NUMBER(10) := SEQ_MATRIZ_FUNCION.NEXTVAL;
    v_combo NUMBER(12) := SEQ_MATRIZ_COMBINACION.NEXTVAL;
    v_asig1 NUMBER(10) := SEQ_USUARIO_ROL_UNIDAD.NEXTVAL;
    v_asig2 NUMBER(10) := SEQ_USUARIO_ROL_UNIDAD.NEXTVAL;
    v_vigencia BOOLEAN := FALSE;
    v_revocacion BOOLEAN := FALSE;
    v_suplencia BOOLEAN := FALSE;
    v_operacion BOOLEAN := FALSE;
    v_secuencias PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_secuencias FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME IN ('SEQ_URU_EVENTO','SEQ_SUPLENCIA_FUNCIONAL','SEQ_OPERACION_APROVISIONAMIENTO')
       AND INCREMENT_BY = 1 AND CACHE_SIZE = 0 AND CYCLE_FLAG = 'N';
    IF v_secuencias <> 3 THEN
        RAISE_APPLICATION_ERROR(-20930, 'T008 fallo: secuencias 008.1 ausentes o incompatibles');
    END IF;
    INSERT INTO USUARIO (ID_USUARIO, KEYCLOAK_ID, LOGIN, NOMBRE_COMPLETO, CORREO, CREADO_POR)
    VALUES (v_u1, '00000000-0000-0000-0000-000000000081', 'test008a_' || v_u1,
            'Titular prueba 008', 'test008a_' || v_u1 || '@example.test', 'TEST_008');
    INSERT INTO USUARIO (ID_USUARIO, KEYCLOAK_ID, LOGIN, NOMBRE_COMPLETO, CORREO, CREADO_POR)
    VALUES (v_u2, '00000000-0000-0000-0000-000000000082', 'test008b_' || v_u2,
            'Suplente prueba 008', 'test008b_' || v_u2 || '@example.test', 'TEST_008');
    INSERT INTO EXPEDIENTE_INSTITUCIONAL
        (ID_EXPEDIENTE,CODIGO,ASUNTO,MODULO_ORIGEN,REFERENCIA_CASO_USO,CLASIFICACION,CREADO_POR)
    VALUES (v_exp, 'TEST-008-' || v_exp, 'Designacion prueba', 'SEGURIDAD', 'TEST_008', 'INTERNO', 'TEST_008');
    INSERT INTO DOCUMENTO_SERIE
        (ID_SERIE,ID_TIPO_DOC,ID_EXPEDIENTE,TITULO,CLASIFICACION_PROPUESTA,CREADO_POR)
    VALUES (v_serie, 1, v_exp, 'Designacion ' || v_serie, 'INTERNO', 'TEST_008');
    INSERT INTO DOCUMENTO
        (ID_DOCUMENTO,ID_TIPO_DOC,NOMBRE_ORIGINAL,MIME_TYPE,TAMANO_BYTES,HASH_SHA256,ID_USUARIO_CARGA,ID_DOCUMENTO_SERIE,NUMERO_VERSION)
    VALUES (v_doc,1,'designacion.pdf','application/pdf',1,RPAD('8',64,'8'),v_u1,v_serie,1);
    INSERT INTO MATRIZ_FUNCIONAL_VERSION
        (ID_VERSION,CODIGO_VERSION,ID_DOCUMENTO_APROBACION,VIGENTE_DESDE,CREADO_POR)
    VALUES (v_mv,'TEST-008-' || v_mv,v_doc,TRUNC(SYSDATE),'TEST_008');
    INSERT INTO MATRIZ_FUNCION (ID_FUNCION,ID_VERSION,CODIGO,DESCRIPCION)
    VALUES (v_fun,v_mv,'FUNC_008_' || v_fun,'Funcion prueba 008');
    INSERT INTO MATRIZ_FUNCION_PERFIL_UNIDAD
        (ID_COMBINACION,ID_VERSION,ID_FUNCION,ID_ROL,ID_UNIDAD,ID_APROBADOR,ID_REGISTRADOR,ID_DOCUMENTO_APROBACION,VIGENTE_DESDE,CREADO_POR)
    VALUES (v_combo,v_mv,v_fun,1,1,v_u1,v_u2,v_doc,TRUNC(SYSDATE),'TEST_008');
    INSERT INTO USUARIO_ROL_UNIDAD
        (ID_USR_ROL_UNIDAD,ID_USUARIO,ID_ROL,ID_UNIDAD,ASIGNADO_POR,ID_COMBINACION_MATRIZ,ID_DOCUMENTO_FORMAL)
    VALUES (v_asig1,v_u1,1,1,'TEST_008',v_combo,v_doc);
    INSERT INTO USUARIO_ROL_UNIDAD
        (ID_USR_ROL_UNIDAD,ID_USUARIO,ID_ROL,ID_UNIDAD,ASIGNADO_POR,ID_COMBINACION_MATRIZ,ID_DOCUMENTO_FORMAL)
    VALUES (v_asig2,v_u2,1,1,'TEST_008',v_combo,v_doc);
    BEGIN
        INSERT INTO USUARIO_ROL_UNIDAD
            (ID_USR_ROL_UNIDAD,ID_USUARIO,ID_ROL,ID_UNIDAD,ASIGNADO_POR,FECHA_INICIO,FECHA_FIN)
        VALUES (SEQ_USUARIO_ROL_UNIDAD.NEXTVAL,v_u1,2,1,'TEST_008',TRUNC(SYSDATE),TRUNC(SYSDATE)-1);
    EXCEPTION WHEN OTHERS THEN IF SQLCODE=-2290 THEN v_vigencia:=TRUE; ELSE RAISE; END IF;
    END;
    INSERT INTO SUPLENCIA_FUNCIONAL
        (ID_SUPLENCIA,ID_ASIGNACION_TITULAR,ID_ASIGNACION_SUPLENTE,INICIO,FIN,ID_AUTORIDAD,ID_DOCUMENTO_FORMAL,CREADO_POR)
    VALUES (SEQ_SUPLENCIA_FUNCIONAL.NEXTVAL,v_asig1,v_asig2,TRUNC(SYSDATE),TRUNC(SYSDATE)+1,v_u1,v_doc,'TEST_008');
    BEGIN
        INSERT INTO SUPLENCIA_FUNCIONAL
            (ID_SUPLENCIA,ID_ASIGNACION_TITULAR,ID_ASIGNACION_SUPLENTE,INICIO,FIN,ID_AUTORIDAD,ID_DOCUMENTO_FORMAL,CREADO_POR)
        VALUES (SEQ_SUPLENCIA_FUNCIONAL.NEXTVAL,v_asig1,v_asig1,TRUNC(SYSDATE)+2,TRUNC(SYSDATE)+3,v_u1,v_doc,'TEST_008');
    EXCEPTION WHEN OTHERS THEN IF SQLCODE=-2290 THEN v_suplencia:=TRUE; ELSE RAISE; END IF;
    END;
    BEGIN
        UPDATE USUARIO_ROL_UNIDAD
           SET REVOCADA_EN = SYSTIMESTAMP,
               REVOCADA_POR = NULL
         WHERE ID_USR_ROL_UNIDAD = v_asig2;
    EXCEPTION WHEN OTHERS THEN IF SQLCODE=-2290 THEN v_revocacion:=TRUE; ELSE RAISE; END IF;
    END;
    UPDATE USUARIO_ROL_UNIDAD
       SET REVOCADA_EN = SYSTIMESTAMP,
           REVOCADA_POR = 'TEST_008',
           MOTIVO_REVOCACION = 'Revocacion controlada de prueba'
     WHERE ID_USR_ROL_UNIDAD = v_asig2;
    INSERT INTO OPERACION_APROVISIONAMIENTO
        (ID_OPERACION,CLAVE_IDEMPOTENTE,HASH_PAYLOAD,ID_USUARIO_OBJETIVO,KEYCLOAK_ID,ESTADO_TECNICO,ERROR_RECUPERABLE,CREADO_POR)
    VALUES (SEQ_OPERACION_APROVISIONAMIENTO.NEXTVAL,'TEST-008-RECUP-' || v_u1,RPAD('9',64,'9'),v_u1,
            '00000000-0000-0000-0000-000000000081','KEYCLOAK_CREADO_DESHABILITADO','S','TEST_008');
    BEGIN
        INSERT INTO OPERACION_APROVISIONAMIENTO
            (ID_OPERACION,CLAVE_IDEMPOTENTE,HASH_PAYLOAD,ESTADO_TECNICO,ERROR_RECUPERABLE,CREADO_POR)
        VALUES (SEQ_OPERACION_APROVISIONAMIENTO.NEXTVAL,'TEST-008-RECUP-' || v_u1,RPAD('9',64,'9'),'ORACLE_PENDIENTE','S','TEST_008');
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN v_operacion:=TRUE;
    END;
    IF NOT v_vigencia OR NOT v_revocacion OR NOT v_suplencia OR NOT v_operacion THEN
        RAISE_APPLICATION_ERROR(-20931, 'T008 fallo: vigencia, suplencia o provision no rechazo');
    END IF;
    DBMS_OUTPUT.PUT_LINE('T008 OK: 008.1, vigencia, suplencia y provision recuperable validadas.');
END;
/

ROLLBACK TO T008_VIGENCIA;
PROMPT T008 finalizada; filas de prueba revertidas.
