-- ============================================================================
-- PIIP MIDAGRI - Verificador manual de solo lectura 012 - Reconciliacion
-- Archivo     : 012_responsables_participantes_reconciliation_test.sql
-- Esquema     : KALLPA_PIIP
-- Modulo      : portafolio
-- Proposito   : emitir evidencia diagnostica de la huella fisica declarada por
--               012: tablas, columnas, defaults, secuencias, constraints,
--               referencias e indices.
-- Dependencia : diccionario Oracle del esquema KALLPA_PIIP. No presupone que
--               012 este vigente; la evidencia debe ser revisada por el DBA.
-- Transaccion : solo consultas a USER_*. No contiene DDL, DML, COMMIT,
--               ROLLBACK ni referencias a NEXTVAL/CURRVAL.
-- Errores     : no aborta por discrepancias; cada fila informa RESULTADO.
-- Auditoria   : conservar la salida completa como evidencia de reconciliacion.
-- Orden       : tablas, columnas/defaults, secuencias, constraints/FK/CHECK e
--               indices. No modifica objetos ni datos.
-- Compensacion: no aplicable; el script es estrictamente de solo lectura.
-- Ejecucion   : SQL Developer (F5), SQLcl o SQL*Plus por DBA autorizado.
-- ============================================================================

SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON

PROMPT [012-reconciliation] Tablas esperadas...
DECLARE
    v_ok PLS_INTEGER := 0;
BEGIN
    FOR r IN (
        WITH esperadas (TABLE_NAME) AS (
            SELECT 'PARTICIPANTE_PERSONA' FROM DUAL UNION ALL
            SELECT 'PROYECTO_PARTICIPANTE_PERSONA' FROM DUAL UNION ALL
            SELECT 'PROYECTO_PARTICIPANTE_UNIDAD' FROM DUAL
        )
        SELECT e.TABLE_NAME, t.TABLE_NAME AS REAL_TABLE_NAME
          FROM esperadas e LEFT JOIN USER_TABLES t ON t.TABLE_NAME = e.TABLE_NAME
         ORDER BY e.TABLE_NAME
    ) LOOP
        IF r.REAL_TABLE_NAME IS NOT NULL THEN v_ok := v_ok + 1; END IF;
        DBMS_OUTPUT.PUT_LINE('TIPO=TABLA;ESPERADA=' || r.TABLE_NAME ||
            ';ENCONTRADA=' || CASE WHEN r.REAL_TABLE_NAME IS NULL THEN 'N' ELSE 'S' END ||
            ';RESULTADO=' || CASE WHEN r.REAL_TABLE_NAME IS NULL THEN 'FALTA' ELSE 'OK' END);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('RESUMEN=TABLAS;OK=' || v_ok || '/3');
END;
/

PROMPT [012-reconciliation] Columnas, tipos y nulabilidad esperados; defaults declarados...
PROMPT [012-reconciliation] NOTA: USER_TAB_COLUMNS.DATA_DEFAULT es LONG; no se consulta ni compara para evitar ORA-00932.
DECLARE
    v_ok PLS_INTEGER := 0;
    v_total PLS_INTEGER := 0;
BEGIN
    FOR r IN (
        WITH esperadas (TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_PRECISION, DATA_SCALE,
                         CHAR_LENGTH, CHAR_USED, NULLABLE, DEFAULT_ESPERADO) AS (
            SELECT 'PARTICIPANTE_PERSONA','ID_PARTICIPANTE','NUMBER',12,0,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PARTICIPANTE_PERSONA','ID_USUARIO','NUMBER',10,0,NULL,NULL,'Y',NULL FROM DUAL UNION ALL SELECT 'PARTICIPANTE_PERSONA','NOMBRES_COMPLETOS','VARCHAR2',NULL,NULL,300,'C','N',NULL FROM DUAL UNION ALL SELECT 'PARTICIPANTE_PERSONA','INSTITUCION','VARCHAR2',NULL,NULL,200,'C','Y',NULL FROM DUAL UNION ALL SELECT 'PARTICIPANTE_PERSONA','FUNCION','VARCHAR2',NULL,NULL,200,'C','Y',NULL FROM DUAL UNION ALL SELECT 'PARTICIPANTE_PERSONA','CLASIFICACION','VARCHAR2',NULL,NULL,20,'C','N','''RESTRINGIDO''' FROM DUAL UNION ALL
            SELECT 'PROYECTO_PARTICIPANTE_PERSONA','ID_PROY_PART_PERSONA','NUMBER',12,0,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_PERSONA','ID_PROYECTO','NUMBER',12,0,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_PERSONA','ID_PARTICIPANTE','NUMBER',12,0,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_PERSONA','INICIO','DATE',NULL,NULL,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_PERSONA','FIN','DATE',NULL,NULL,NULL,NULL,'Y',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_PERSONA','ID_ACTOR','NUMBER',10,0,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_PERSONA','CREADO_POR','VARCHAR2',NULL,NULL,100,'C','N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_PERSONA','FECHA_CREACION','TIMESTAMP',NULL,6,NULL,NULL,'N','SYSTIMESTAMP' FROM DUAL UNION ALL
            SELECT 'PROYECTO_PARTICIPANTE_UNIDAD','ID_PROY_PART_UNIDAD','NUMBER',12,0,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_UNIDAD','ID_PROYECTO','NUMBER',12,0,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_UNIDAD','ID_UNIDAD','NUMBER',10,0,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_UNIDAD','INICIO','DATE',NULL,NULL,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_UNIDAD','FIN','DATE',NULL,NULL,NULL,NULL,'Y',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_UNIDAD','ID_ACTOR','NUMBER',10,0,NULL,NULL,'N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_UNIDAD','CREADO_POR','VARCHAR2',NULL,NULL,100,'C','N',NULL FROM DUAL UNION ALL SELECT 'PROYECTO_PARTICIPANTE_UNIDAD','FECHA_CREACION','TIMESTAMP',NULL,6,NULL,NULL,'N','SYSTIMESTAMP' FROM DUAL
        )
        SELECT e.*, c.DATA_TYPE REAL_DATA_TYPE, c.DATA_PRECISION REAL_PRECISION, c.DATA_SCALE REAL_SCALE, c.CHAR_LENGTH REAL_CHAR_LENGTH, c.CHAR_USED REAL_CHAR_USED, c.NULLABLE REAL_NULLABLE
          FROM esperadas e LEFT JOIN USER_TAB_COLUMNS c ON c.TABLE_NAME=e.TABLE_NAME AND c.COLUMN_NAME=e.COLUMN_NAME
         ORDER BY e.TABLE_NAME, e.COLUMN_NAME
    ) LOOP
        v_total := v_total + 1;
        IF r.REAL_DATA_TYPE = r.DATA_TYPE AND NVL(r.REAL_PRECISION,-1) = NVL(r.DATA_PRECISION,-1) AND NVL(r.REAL_SCALE,-1) = NVL(r.DATA_SCALE,-1) AND NVL(r.REAL_CHAR_LENGTH,-1) = NVL(r.CHAR_LENGTH,-1) AND NVL(r.REAL_CHAR_USED,'-') = NVL(r.CHAR_USED,'-') AND NVL(r.REAL_NULLABLE,'-') = r.NULLABLE THEN v_ok := v_ok + 1; END IF;
        DBMS_OUTPUT.PUT_LINE('TIPO=COLUMNA;TABLA=' || r.TABLE_NAME || ';COLUMNA=' || r.COLUMN_NAME || ';ESPERADO=' || r.DATA_TYPE || ';PRECISION=' || NVL(TO_CHAR(r.DATA_PRECISION),'<NULL>') || ';SCALE=' || NVL(TO_CHAR(r.DATA_SCALE),'<NULL>') || ';CHAR_LENGTH=' || NVL(TO_CHAR(r.CHAR_LENGTH),'<NULL>') || ';CHAR_USED=' || NVL(r.CHAR_USED,'<NULL>') || ';NULLABLE=' || r.NULLABLE || ';DEFAULT_DECLARADO=' || NVL(r.DEFAULT_ESPERADO,'<NULL>') || ';DEFAULT_REAL=NO_VERIFICADO_LONG' || ';RESULTADO=' || CASE WHEN r.REAL_DATA_TYPE = r.DATA_TYPE AND NVL(r.REAL_PRECISION,-1)=NVL(r.DATA_PRECISION,-1) AND NVL(r.REAL_SCALE,-1)=NVL(r.DATA_SCALE,-1) AND NVL(r.REAL_CHAR_LENGTH,-1)=NVL(r.CHAR_LENGTH,-1) AND NVL(r.REAL_CHAR_USED,'-')=NVL(r.CHAR_USED,'-') AND NVL(r.REAL_NULLABLE,'-')=r.NULLABLE THEN 'OK_SIN_DEFAULT' ELSE 'DIFERENCIA' END);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('RESUMEN=COLUMNAS;OK_SIN_DEFAULT=' || v_ok || '/' || v_total || ';DEFAULTS_REQUIEREN_REVISION_DBA_SEPARADA');
END;
/

PROMPT [012-reconciliation] Secuencias esperadas (sin consumir valores)...
DECLARE
    v_ok PLS_INTEGER := 0;
BEGIN
    FOR r IN (
        WITH esperadas (SEQUENCE_NAME) AS (SELECT 'SEQ_PARTICIPANTE_PERSONA' FROM DUAL UNION ALL SELECT 'SEQ_PROY_PART_PERSONA' FROM DUAL UNION ALL SELECT 'SEQ_PROY_PART_UNIDAD' FROM DUAL)
        SELECT e.SEQUENCE_NAME, s.INCREMENT_BY, s.CACHE_SIZE, s.CYCLE_FLAG FROM esperadas e LEFT JOIN USER_SEQUENCES s ON s.SEQUENCE_NAME=e.SEQUENCE_NAME ORDER BY e.SEQUENCE_NAME
    ) LOOP
        IF r.INCREMENT_BY=1 AND r.CACHE_SIZE=0 AND r.CYCLE_FLAG='N' THEN v_ok:=v_ok+1; END IF;
        DBMS_OUTPUT.PUT_LINE('TIPO=SECUENCIA;NOMBRE=' || r.SEQUENCE_NAME || ';INCREMENT_BY=' || NVL(TO_CHAR(r.INCREMENT_BY),'<NULL>') || ';CACHE_SIZE=' || NVL(TO_CHAR(r.CACHE_SIZE),'<NULL>') || ';CYCLE_FLAG=' || NVL(r.CYCLE_FLAG,'<NULL>') || ';RESULTADO=' || CASE WHEN r.INCREMENT_BY=1 AND r.CACHE_SIZE=0 AND r.CYCLE_FLAG='N' THEN 'OK' ELSE 'DIFERENCIA' END);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('RESUMEN=SECUENCIAS;OK=' || v_ok || '/3');
END;
/

PROMPT [012-reconciliation] PK, UK, FK y CHECK esperados, incluidos estado y referencias...
DECLARE
    v_ok PLS_INTEGER := 0; v_total PLS_INTEGER := 0;
BEGIN
    FOR r IN (
        WITH esperadas (CONSTRAINT_NAME,TABLE_NAME,CONSTRAINT_TYPE,TABLA_REFERIDA) AS (
            SELECT 'PK_PARTICIPANTE_PERSONA','PARTICIPANTE_PERSONA','P',NULL FROM DUAL UNION ALL SELECT 'FK_PP_USUARIO','PARTICIPANTE_PERSONA','R','USUARIO' FROM DUAL UNION ALL SELECT 'CK_PP_CLASIFICACION','PARTICIPANTE_PERSONA','C',NULL FROM DUAL UNION ALL SELECT 'CK_PP_DATOS_MINIMOS','PARTICIPANTE_PERSONA','C',NULL FROM DUAL UNION ALL
            SELECT 'PK_PROYECTO_PARTICIPANTE_PERSONA','PROYECTO_PARTICIPANTE_PERSONA','P',NULL FROM DUAL UNION ALL SELECT 'UK_PPP_PROY_PART','PROYECTO_PARTICIPANTE_PERSONA','U',NULL FROM DUAL UNION ALL SELECT 'FK_PPP_PROYECTO','PROYECTO_PARTICIPANTE_PERSONA','R','PROYECTO' FROM DUAL UNION ALL SELECT 'FK_PPP_PARTICIPANTE','PROYECTO_PARTICIPANTE_PERSONA','R','PARTICIPANTE_PERSONA' FROM DUAL UNION ALL SELECT 'FK_PPP_ACTOR','PROYECTO_PARTICIPANTE_PERSONA','R','USUARIO' FROM DUAL UNION ALL SELECT 'CK_PPP_VIGENCIA','PROYECTO_PARTICIPANTE_PERSONA','C',NULL FROM DUAL UNION ALL
            SELECT 'PK_PROYECTO_PARTICIPANTE_UNIDAD','PROYECTO_PARTICIPANTE_UNIDAD','P',NULL FROM DUAL UNION ALL SELECT 'UK_PPU_PROY_UNI','PROYECTO_PARTICIPANTE_UNIDAD','U',NULL FROM DUAL UNION ALL SELECT 'FK_PPU_PROYECTO','PROYECTO_PARTICIPANTE_UNIDAD','R','PROYECTO' FROM DUAL UNION ALL SELECT 'FK_PPU_UNIDAD','PROYECTO_PARTICIPANTE_UNIDAD','R','UNIDAD_EJECUTORA' FROM DUAL UNION ALL SELECT 'FK_PPU_ACTOR','PROYECTO_PARTICIPANTE_UNIDAD','R','USUARIO' FROM DUAL UNION ALL SELECT 'CK_PPU_VIGENCIA','PROYECTO_PARTICIPANTE_UNIDAD','C',NULL FROM DUAL
        )
        SELECT e.*, c.CONSTRAINT_TYPE REAL_TYPE, c.STATUS, c.VALIDATED, c.SEARCH_CONDITION_VC, rc.TABLE_NAME REAL_TABLA_REFERIDA
          FROM esperadas e LEFT JOIN USER_CONSTRAINTS c ON c.CONSTRAINT_NAME=e.CONSTRAINT_NAME AND c.TABLE_NAME=e.TABLE_NAME LEFT JOIN USER_CONSTRAINTS rc ON rc.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME ORDER BY e.TABLE_NAME,e.CONSTRAINT_NAME
    ) LOOP
        v_total:=v_total+1;
        IF r.REAL_TYPE=r.CONSTRAINT_TYPE AND r.STATUS='ENABLED' AND NVL(r.REAL_TABLA_REFERIDA,'<NULL>')=NVL(r.TABLA_REFERIDA,'<NULL>') THEN v_ok:=v_ok+1; END IF;
        DBMS_OUTPUT.PUT_LINE('TIPO=CONSTRAINT;NOMBRE=' || r.CONSTRAINT_NAME || ';TABLA=' || r.TABLE_NAME || ';TIPO_ESPERADO=' || r.CONSTRAINT_TYPE || ';TIPO_REAL=' || NVL(r.REAL_TYPE,'<NULL>') || ';ESTADO=' || NVL(r.STATUS,'<NULL>') || ';VALIDADO=' || NVL(r.VALIDATED,'<NULL>') || ';REFERENCIA_ESPERADA=' || NVL(r.TABLA_REFERIDA,'<NULL>') || ';REFERENCIA_REAL=' || NVL(r.REAL_TABLA_REFERIDA,'<NULL>') || ';CHECK_REAL=' || NVL(r.SEARCH_CONDITION_VC,'<NULL>') || ';RESULTADO=' || CASE WHEN r.REAL_TYPE=r.CONSTRAINT_TYPE AND r.STATUS='ENABLED' AND NVL(r.REAL_TABLA_REFERIDA,'<NULL>')=NVL(r.TABLA_REFERIDA,'<NULL>') THEN 'OK' ELSE 'DIFERENCIA' END);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('RESUMEN=CONSTRAINTS;OK=' || v_ok || '/' || v_total || ';CHECKS_DEBEN_REVISARSE_CONTRA_012');
END;
/

PROMPT [012-reconciliation] Columnas de referencias FK esperadas...
DECLARE
    v_ok PLS_INTEGER := 0; v_total PLS_INTEGER := 0;
BEGIN
    FOR r IN (
        WITH esperadas (CONSTRAINT_NAME,CHILD_COLUMN,PARENT_TABLE,PARENT_COLUMN) AS (
            SELECT 'FK_PP_USUARIO','ID_USUARIO','USUARIO','ID_USUARIO' FROM DUAL UNION ALL
            SELECT 'FK_PPP_PROYECTO','ID_PROYECTO','PROYECTO','ID_PROYECTO' FROM DUAL UNION ALL
            SELECT 'FK_PPP_PARTICIPANTE','ID_PARTICIPANTE','PARTICIPANTE_PERSONA','ID_PARTICIPANTE' FROM DUAL UNION ALL
            SELECT 'FK_PPP_ACTOR','ID_ACTOR','USUARIO','ID_USUARIO' FROM DUAL UNION ALL
            SELECT 'FK_PPU_PROYECTO','ID_PROYECTO','PROYECTO','ID_PROYECTO' FROM DUAL UNION ALL
            SELECT 'FK_PPU_UNIDAD','ID_UNIDAD','UNIDAD_EJECUTORA','ID_UNIDAD' FROM DUAL UNION ALL
            SELECT 'FK_PPU_ACTOR','ID_ACTOR','USUARIO','ID_USUARIO' FROM DUAL
        )
        SELECT e.*, cc.COLUMN_NAME REAL_CHILD_COLUMN, pc.TABLE_NAME REAL_PARENT_TABLE,
               pc.COLUMN_NAME REAL_PARENT_COLUMN
          FROM esperadas e
          LEFT JOIN USER_CONSTRAINTS c ON c.CONSTRAINT_NAME=e.CONSTRAINT_NAME
          LEFT JOIN USER_CONS_COLUMNS cc ON cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME AND cc.POSITION=1
          LEFT JOIN USER_CONS_COLUMNS pc ON pc.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME AND pc.POSITION=1
         ORDER BY e.CONSTRAINT_NAME
    ) LOOP
        v_total:=v_total+1;
        IF r.REAL_CHILD_COLUMN=r.CHILD_COLUMN AND r.REAL_PARENT_TABLE=r.PARENT_TABLE AND r.REAL_PARENT_COLUMN=r.PARENT_COLUMN THEN v_ok:=v_ok+1; END IF;
        DBMS_OUTPUT.PUT_LINE('TIPO=REFERENCIA;FK=' || r.CONSTRAINT_NAME || ';COLUMNA_HIJA_ESPERADA=' || r.CHILD_COLUMN || ';COLUMNA_HIJA_REAL=' || NVL(r.REAL_CHILD_COLUMN,'<NULL>') || ';TABLA_PADRE_ESPERADA=' || r.PARENT_TABLE || ';TABLA_PADRE_REAL=' || NVL(r.REAL_PARENT_TABLE,'<NULL>') || ';COLUMNA_PADRE_ESPERADA=' || r.PARENT_COLUMN || ';COLUMNA_PADRE_REAL=' || NVL(r.REAL_PARENT_COLUMN,'<NULL>') || ';RESULTADO=' || CASE WHEN r.REAL_CHILD_COLUMN=r.CHILD_COLUMN AND r.REAL_PARENT_TABLE=r.PARENT_TABLE AND r.REAL_PARENT_COLUMN=r.PARENT_COLUMN THEN 'OK' ELSE 'DIFERENCIA' END);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('RESUMEN=REFERENCIAS;OK=' || v_ok || '/' || v_total);
END;
/

PROMPT [012-reconciliation] Columnas y orden de PK/UK/indices auxiliares esperados...
DECLARE
    v_ok PLS_INTEGER := 0; v_total PLS_INTEGER := 0;
BEGIN
    FOR r IN (
        WITH esperadas (INDEX_NAME,TABLE_NAME,UNIQUENESS,COLUMN_POSITION,COLUMN_NAME) AS (
            SELECT 'PK_PARTICIPANTE_PERSONA','PARTICIPANTE_PERSONA','UNIQUE',1,'ID_PARTICIPANTE' FROM DUAL UNION ALL SELECT 'IDX_PP_USUARIO','PARTICIPANTE_PERSONA','NONUNIQUE',1,'ID_USUARIO' FROM DUAL UNION ALL SELECT 'PK_PROYECTO_PARTICIPANTE_PERSONA','PROYECTO_PARTICIPANTE_PERSONA','UNIQUE',1,'ID_PROY_PART_PERSONA' FROM DUAL UNION ALL SELECT 'UK_PPP_PROY_PART','PROYECTO_PARTICIPANTE_PERSONA','UNIQUE',1,'ID_PROYECTO' FROM DUAL UNION ALL SELECT 'UK_PPP_PROY_PART','PROYECTO_PARTICIPANTE_PERSONA','UNIQUE',2,'ID_PARTICIPANTE' FROM DUAL UNION ALL SELECT 'IDX_PPP_PROYECTO','PROYECTO_PARTICIPANTE_PERSONA','NONUNIQUE',1,'ID_PROYECTO' FROM DUAL UNION ALL SELECT 'PK_PROYECTO_PARTICIPANTE_UNIDAD','PROYECTO_PARTICIPANTE_UNIDAD','UNIQUE',1,'ID_PROY_PART_UNIDAD' FROM DUAL UNION ALL SELECT 'UK_PPU_PROY_UNI','PROYECTO_PARTICIPANTE_UNIDAD','UNIQUE',1,'ID_PROYECTO' FROM DUAL UNION ALL SELECT 'UK_PPU_PROY_UNI','PROYECTO_PARTICIPANTE_UNIDAD','UNIQUE',2,'ID_UNIDAD' FROM DUAL UNION ALL SELECT 'IDX_PPU_PROYECTO','PROYECTO_PARTICIPANTE_UNIDAD','NONUNIQUE',1,'ID_PROYECTO' FROM DUAL
        )
        SELECT e.*, i.UNIQUENESS REAL_UNIQUENESS, i.STATUS, ic.COLUMN_NAME REAL_COLUMN_NAME FROM esperadas e LEFT JOIN USER_INDEXES i ON i.INDEX_NAME=e.INDEX_NAME AND i.TABLE_NAME=e.TABLE_NAME LEFT JOIN USER_IND_COLUMNS ic ON ic.INDEX_NAME=e.INDEX_NAME AND ic.COLUMN_POSITION=e.COLUMN_POSITION ORDER BY e.TABLE_NAME,e.INDEX_NAME,e.COLUMN_POSITION
    ) LOOP
        v_total:=v_total+1;
        IF r.REAL_UNIQUENESS=r.UNIQUENESS AND r.STATUS='VALID' AND r.REAL_COLUMN_NAME=r.COLUMN_NAME THEN v_ok:=v_ok+1; END IF;
        DBMS_OUTPUT.PUT_LINE('TIPO=INDICE;NOMBRE=' || r.INDEX_NAME || ';TABLA=' || r.TABLE_NAME || ';POSICION=' || r.COLUMN_POSITION || ';COLUMNA_ESPERADA=' || r.COLUMN_NAME || ';COLUMNA_REAL=' || NVL(r.REAL_COLUMN_NAME,'<NULL>') || ';UNICIDAD=' || NVL(r.REAL_UNIQUENESS,'<NULL>') || ';ESTADO=' || NVL(r.STATUS,'<NULL>') || ';RESULTADO=' || CASE WHEN r.REAL_UNIQUENESS=r.UNIQUENESS AND r.STATUS='VALID' AND r.REAL_COLUMN_NAME=r.COLUMN_NAME THEN 'OK' ELSE 'DIFERENCIA' END);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('RESUMEN=INDICES;OK=' || v_ok || '/' || v_total);
END;
/

PROMPT [012-reconciliation] Verificador terminado. Conservar toda la salida; no se realizaron cambios.
