-- Diagnostico de solo lectura de la semilla 021 y bootstrap 021.1.
-- No contiene DDL, DML, COMMIT, ROLLBACK ni SAVEPOINT.
SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT [021] Unidad raiz esperada
SELECT CODIGO_UNIDAD, NOMBRE, ACTIVO
  FROM UNIDAD_EJECUTORA
 WHERE ID_UNIDAD = 1;

PROMPT [021] MATRIZ_FUNCIONAL_VERSION
SELECT COUNT(*) AS TOTAL_MATRIZ_FUNCIONAL_VERSION FROM MATRIZ_FUNCIONAL_VERSION;
SELECT ID_VERSION, CODIGO_VERSION, ID_DOCUMENTO_APROBACION, ACTIVA, VIGENTE_DESDE
  FROM MATRIZ_FUNCIONAL_VERSION
 ORDER BY ID_VERSION;

PROMPT [021] MATRIZ_FUNCION
SELECT COUNT(*) AS TOTAL_MATRIZ_FUNCION FROM MATRIZ_FUNCION;
SELECT ID_FUNCION, ID_VERSION, CODIGO, DESCRIPCION, ACTIVA
  FROM MATRIZ_FUNCION
 ORDER BY ID_FUNCION;

PROMPT [021] MATRIZ_FUNCION_PERFIL_UNIDAD (con ES_BOOTSTRAP si existe)
SELECT COUNT(*) AS TOTAL_MATRIZ_FUNCION_PERFIL_UNIDAD FROM MATRIZ_FUNCION_PERFIL_UNIDAD;
SELECT ID_COMBINACION, ID_VERSION, ID_FUNCION, ID_ROL, ID_UNIDAD,
       ID_APROBADOR, ID_REGISTRADOR, ID_DOCUMENTO_APROBACION, ACTIVA,
       CASE
         WHEN EXISTS (
           SELECT 1 FROM USER_TAB_COLUMNS
           WHERE TABLE_NAME = 'MATRIZ_FUNCION_PERFIL_UNIDAD'
             AND COLUMN_NAME = 'ES_BOOTSTRAP'
         ) THEN (SELECT ES_BOOTSTRAP FROM MATRIZ_FUNCION_PERFIL_UNIDAD m
                  WHERE m.ID_COMBINACION = mfpu.ID_COMBINACION)
         ELSE '(columna no existe)'
       END AS ES_BOOTSTRAP
  FROM MATRIZ_FUNCION_PERFIL_UNIDAD mfpu
 ORDER BY ID_COMBINACION;

PROMPT [021] USUARIO (KEYCLOAK_ID enmascarado)
SELECT COUNT(*) AS TOTAL_USUARIO FROM USUARIO;
SELECT ID_USUARIO, SUBSTR(KEYCLOAK_ID, 1, 8) || '...' AS KEYCLOAK_ID_PREFIJO,
       LOGIN, ACTIVO, LOGIN_SINTETICO
  FROM USUARIO
 ORDER BY ID_USUARIO;

PROMPT [021] USUARIO_ROL_UNIDAD
SELECT COUNT(*) AS TOTAL_USUARIO_ROL_UNIDAD FROM USUARIO_ROL_UNIDAD;
SELECT uru.ID_USR_ROL_UNIDAD, uru.ID_USUARIO, r.NOMBRE_ROL, uru.ID_UNIDAD,
       uru.ID_COMBINACION_MATRIZ, uru.ACTIVO, uru.FECHA_FIN, uru.REVOCADA_EN
  FROM USUARIO_ROL_UNIDAD uru
  JOIN ROL r ON r.ID_ROL = uru.ID_ROL
 ORDER BY uru.ID_USR_ROL_UNIDAD;

PROMPT [021] Auditoria y marcador tecnico
SELECT COUNT(*) AS TOTAL_AUDITORIA_EVENTO_021
  FROM AUDITORIA_EVENTO
 WHERE TIPO_EVENTO = 'INICIALIZACION_GLOBAL_ADMIN';
SELECT ID_EVENTO, ENTIDAD_TIPO, ENTIDAD_ID, FECHA_EVENTO, PROCESADO
  FROM AUDITORIA_EVENTO
 WHERE TIPO_EVENTO = 'INICIALIZACION_GLOBAL_ADMIN'
 ORDER BY ID_EVENTO;
SELECT COUNT(*) AS TOTAL_AUDITORIA_ACCESO_021
  FROM AUDITORIA_ACCESO
 WHERE ENDPOINT LIKE '/internal/seed/021%';
SELECT COMMENTS AS COMENTARIO_MATRIZ_FUNCIONAL_VERSION
  FROM USER_TAB_COMMENTS
 WHERE TABLE_NAME = 'MATRIZ_FUNCIONAL_VERSION';

PROMPT [021] Presencia de columna ES_BOOTSTRAP
SELECT COUNT(*) AS TOTAL_ES_BOOTSTRAP_COL
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'MATRIZ_FUNCION_PERFIL_UNIDAD'
   AND COLUMN_NAME = 'ES_BOOTSTRAP';

DECLARE
    v_versiones PLS_INTEGER;
    v_funciones PLS_INTEGER;
    v_bootstrap PLS_INTEGER;
    v_usuarios_global PLS_INTEGER;
    v_asignaciones_global PLS_INTEGER;
    v_auditoria PLS_INTEGER;
    v_es_bootstrap_col PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_versiones FROM MATRIZ_FUNCIONAL_VERSION;
    SELECT COUNT(*) INTO v_funciones FROM MATRIZ_FUNCION
     WHERE CODIGO = 'ADMINISTRADOR_PIIP';
    SELECT COUNT(*) INTO v_bootstrap
      FROM MATRIZ_FUNCION_PERFIL_UNIDAD
     WHERE ES_BOOTSTRAP = 'S';
    SELECT COUNT(*) INTO v_usuarios_global
      FROM USUARIO_ROL_UNIDAD uru
      JOIN ROL r ON r.ID_ROL = uru.ID_ROL
     WHERE r.NOMBRE_ROL = 'GlobalAdmin';
    SELECT COUNT(*) INTO v_asignaciones_global
      FROM USUARIO_ROL_UNIDAD uru
      JOIN ROL r ON r.ID_ROL = uru.ID_ROL
     WHERE r.NOMBRE_ROL = 'GlobalAdmin'
       AND uru.REVOCADA_EN IS NULL AND uru.FECHA_FIN IS NULL;
    SELECT COUNT(*) INTO v_auditoria FROM AUDITORIA_EVENTO
     WHERE TIPO_EVENTO = 'INICIALIZACION_GLOBAL_ADMIN';
    SELECT COUNT(*) INTO v_es_bootstrap_col
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'MATRIZ_FUNCION_PERFIL_UNIDAD'
       AND COLUMN_NAME = 'ES_BOOTSTRAP';

    IF v_versiones = 0 AND v_funciones = 0 AND v_bootstrap = 0
       AND v_usuarios_global = 0 AND v_asignaciones_global = 0
       AND v_auditoria = 0 AND v_es_bootstrap_col = 0 THEN
        DBMS_OUTPUT.PUT_LINE('SEMILLA_021_ESTADO=NO_APLICADA');
    ELSIF v_versiones = 1 AND v_funciones = 1 AND v_bootstrap = 1
       AND v_usuarios_global = 1 AND v_asignaciones_global = 1
       AND v_auditoria >= 1 THEN
        DBMS_OUTPUT.PUT_LINE('SEMILLA_021_ESTADO=APLICADA');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SEMILLA_021_ESTADO=PARCIAL');
    END IF;
END;
/
