-- Diagnostico de solo lectura para la carga manual 023.
-- No ejecuta DML ni imprime valores sensibles completos.
SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE

ACCEPT ID_TIPO_DOC_POI CHAR PROMPT 'ID_TIPO_DOC POI: '
ACCEPT ID_UNIDAD_PLANEAMIENTO CHAR PROMPT 'ID_UNIDAD de planeamiento: '
ACCEPT ID_USUARIO_PLANEAMIENTO CHAR PROMPT 'ID_USUARIO de planeamiento: '
ACCEPT NOMBRE_DOCUMENTO CHAR PROMPT 'Titulo del documento: '
ACCEPT NOMBRE_ORIGINAL CHAR PROMPT 'Nombre original del archivo: '
ACCEPT MIME_TYPE CHAR PROMPT 'Tipo MIME: '
ACCEPT TAMANO_BYTES CHAR PROMPT 'Tamano en bytes: '
ACCEPT HASH_SHA256 CHAR PROMPT 'Hash SHA-256: ' HIDE
ACCEPT NOMBRE_STORAGE CHAR PROMPT 'Nombre o ruta de almacenamiento: ' HIDE

DECLARE
    v_conteo PLS_INTEGER;
    PROCEDURE validar_positivo(p_valor VARCHAR2, p_nombre VARCHAR2) IS
    BEGIN
        IF NOT REGEXP_LIKE(TRIM(p_valor), '^[0-9]+$') THEN
            RAISE_APPLICATION_ERROR(-20328, p_nombre || ' debe ser un entero positivo');
        END IF;
        IF TO_NUMBER(TRIM(p_valor)) <= 0 THEN
            RAISE_APPLICATION_ERROR(-20328, p_nombre || ' debe ser un entero positivo');
        END IF;
    END;
BEGIN
    validar_positivo('&&ID_TIPO_DOC_POI', 'ID_TIPO_DOC_POI');
    validar_positivo('&&ID_UNIDAD_PLANEAMIENTO', 'ID_UNIDAD_PLANEAMIENTO');
    validar_positivo('&&ID_USUARIO_PLANEAMIENTO', 'ID_USUARIO_PLANEAMIENTO');
    validar_positivo('&&TAMANO_BYTES', 'TAMANO_BYTES');
    IF NOT REGEXP_LIKE(TRIM('&&HASH_SHA256'), '^[0-9A-Fa-f]{64}$') THEN
        RAISE_APPLICATION_ERROR(-20325, 'HASH_SHA256 debe tener 64 caracteres hexadecimales');
    END IF;

    DBMS_OUTPUT.PUT_LINE('ID_TIPO_DOC_POI=' || TRIM('&&ID_TIPO_DOC_POI'));
    DBMS_OUTPUT.PUT_LINE('ID_UNIDAD_PLANEAMIENTO=' || TRIM('&&ID_UNIDAD_PLANEAMIENTO'));
    DBMS_OUTPUT.PUT_LINE('ID_USUARIO_PLANEAMIENTO=' || TRIM('&&ID_USUARIO_PLANEAMIENTO'));
    DBMS_OUTPUT.PUT_LINE('TAMANO_BYTES=' || TRIM('&&TAMANO_BYTES'));
    DBMS_OUTPUT.PUT_LINE('HASH_SHA256_PREFIJO=' || SUBSTR(TRIM('&&HASH_SHA256'), 1, 8));
    DBMS_OUTPUT.PUT_LINE('NOMBRE_DOCUMENTO_LONGITUD=' || NVL(TO_CHAR(LENGTH('&&NOMBRE_DOCUMENTO')), 'NULL'));
    DBMS_OUTPUT.PUT_LINE('NOMBRE_ORIGINAL_LONGITUD=' || NVL(TO_CHAR(LENGTH('&&NOMBRE_ORIGINAL')), 'NULL'));
    DBMS_OUTPUT.PUT_LINE('MIME_TYPE_LONGITUD=' || NVL(TO_CHAR(LENGTH('&&MIME_TYPE')), 'NULL'));
    DBMS_OUTPUT.PUT_LINE('NOMBRE_STORAGE_LONGITUD=' || NVL(TO_CHAR(LENGTH('&&NOMBRE_STORAGE')), 'NULL'));

    SELECT COUNT(*) INTO v_conteo FROM TIPO_DOCUMENTO
     WHERE ID_TIPO_DOC = TO_NUMBER(TRIM('&&ID_TIPO_DOC_POI'));
    IF v_conteo = 0 THEN
        RAISE_APPLICATION_ERROR(-20322, 'ID_TIPO_DOC_POI no existe en TIPO_DOCUMENTO');
    END IF;
    SELECT COUNT(*) INTO v_conteo FROM UNIDAD_EJECUTORA
     WHERE ID_UNIDAD = TO_NUMBER(TRIM('&&ID_UNIDAD_PLANEAMIENTO'));
    IF v_conteo = 0 THEN
        RAISE_APPLICATION_ERROR(-20323, 'ID_UNIDAD_PLANEAMIENTO no existe en UNIDAD_EJECUTORA');
    END IF;
    SELECT COUNT(*) INTO v_conteo FROM USUARIO
     WHERE ID_USUARIO = TO_NUMBER(TRIM('&&ID_USUARIO_PLANEAMIENTO'));
    IF v_conteo = 0 THEN
        RAISE_APPLICATION_ERROR(-20324, 'ID_USUARIO_PLANEAMIENTO no existe en USUARIO');
    END IF;
    DBMS_OUTPUT.PUT_LINE('Diagnostico 023: referencias requeridas existentes; no se ejecuto DML.');
END;
/

UNDEFINE ID_TIPO_DOC_POI
UNDEFINE ID_UNIDAD_PLANEAMIENTO
UNDEFINE ID_USUARIO_PLANEAMIENTO
UNDEFINE NOMBRE_DOCUMENTO
UNDEFINE NOMBRE_ORIGINAL
UNDEFINE MIME_TYPE
UNDEFINE TAMANO_BYTES
UNDEFINE HASH_SHA256
UNDEFINE NOMBRE_STORAGE
SET DEFINE OFF
