-- Diagnostico de solo lectura para la carga manual 024.
-- No ejecuta DML ni imprime valores sensibles completos.
SET DEFINE ON
SET VERIFY OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE

ACCEPT ID_UNIDAD_PLANEAMIENTO CHAR PROMPT 'ID_UNIDAD de planeamiento: '
ACCEPT ID_COMBINACION_PLANEAMIENTO CHAR PROMPT 'ID_COMBINACION de planeamiento (0 si no aplica): '
ACCEPT KEYCLOAK_ID CHAR PROMPT 'sub UUID de Keycloak: ' HIDE
ACCEPT LOGIN CHAR PROMPT 'Login institucional (vacio si no aplica): '
ACCEPT CORREO_INSTITUCIONAL CHAR PROMPT 'Correo institucional (vacio si no aplica): ' HIDE
ACCEPT NOMBRE_COMPLETO CHAR PROMPT 'Nombre completo (vacio si no aplica): '

DECLARE
    v_conteo PLS_INTEGER;
BEGIN
    IF NOT REGEXP_LIKE(TRIM('&&ID_UNIDAD_PLANEAMIENTO'), '^[0-9]+$') THEN
        RAISE_APPLICATION_ERROR(-20427,
            'ID_UNIDAD_PLANEAMIENTO debe ser un entero positivo');
    END IF;
    IF TO_NUMBER(TRIM('&&ID_UNIDAD_PLANEAMIENTO')) <= 0 THEN
        RAISE_APPLICATION_ERROR(-20427,
            'ID_UNIDAD_PLANEAMIENTO debe ser un entero positivo');
    END IF;
    IF TRIM('&&ID_COMBINACION_PLANEAMIENTO') IS NOT NULL
       AND NOT REGEXP_LIKE(TRIM('&&ID_COMBINACION_PLANEAMIENTO'), '^[0-9]+$') THEN
        RAISE_APPLICATION_ERROR(-20427,
            'ID_COMBINACION_PLANEAMIENTO debe ser 0 o un entero positivo');
    END IF;
    IF TRIM('&&ID_COMBINACION_PLANEAMIENTO') IS NOT NULL
       AND TO_NUMBER(TRIM('&&ID_COMBINACION_PLANEAMIENTO')) < 0 THEN
        RAISE_APPLICATION_ERROR(-20427,
            'ID_COMBINACION_PLANEAMIENTO debe ser 0 o un entero positivo');
    END IF;
    IF NOT REGEXP_LIKE(TRIM('&&KEYCLOAK_ID'),
        '^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$') THEN
        RAISE_APPLICATION_ERROR(-20425, 'KEYCLOAK_ID debe tener formato UUID valido');
    END IF;

    DBMS_OUTPUT.PUT_LINE('ID_UNIDAD_PLANEAMIENTO=' || TRIM('&&ID_UNIDAD_PLANEAMIENTO'));
    DBMS_OUTPUT.PUT_LINE('ID_COMBINACION_PLANEAMIENTO=' || NVL(TRIM('&&ID_COMBINACION_PLANEAMIENTO'), 'NULL'));
    DBMS_OUTPUT.PUT_LINE('KEYCLOAK_ID_PREFIJO=' || SUBSTR(TRIM('&&KEYCLOAK_ID'), 1, 8));
    DBMS_OUTPUT.PUT_LINE('LOGIN_LONGITUD=' || NVL(TO_CHAR(LENGTH('&&LOGIN')), 'NULL'));
    DBMS_OUTPUT.PUT_LINE('CORREO_INSTITUCIONAL_LONGITUD=' || NVL(TO_CHAR(LENGTH('&&CORREO_INSTITUCIONAL')), 'NULL'));
    DBMS_OUTPUT.PUT_LINE('NOMBRE_COMPLETO_LONGITUD=' || NVL(TO_CHAR(LENGTH('&&NOMBRE_COMPLETO')), 'NULL'));

    SELECT COUNT(*) INTO v_conteo FROM UNIDAD_EJECUTORA
     WHERE ID_UNIDAD = TO_NUMBER(TRIM('&&ID_UNIDAD_PLANEAMIENTO'));
    IF v_conteo = 0 THEN
        RAISE_APPLICATION_ERROR(-20423, 'ID_UNIDAD_PLANEAMIENTO no existe en UNIDAD_EJECUTORA');
    END IF;
    SELECT COUNT(*) INTO v_conteo FROM USUARIO
     WHERE KEYCLOAK_ID = TRIM('&&KEYCLOAK_ID');
    IF v_conteo <> 0 THEN
        RAISE_APPLICATION_ERROR(-20424,
            'Ya existe un usuario con ese KEYCLOAK_ID; la carga 024 no es re-ejecutable');
    END IF;
    IF TRIM('&&ID_COMBINACION_PLANEAMIENTO') IS NOT NULL
       AND TO_NUMBER(TRIM('&&ID_COMBINACION_PLANEAMIENTO')) > 0 THEN
        SELECT COUNT(*) INTO v_conteo FROM MATRIZ_FUNCION_PERFIL_UNIDAD
         WHERE ID_COMBINACION = TO_NUMBER(TRIM('&&ID_COMBINACION_PLANEAMIENTO'));
        IF v_conteo = 0 THEN
            RAISE_APPLICATION_ERROR(-20426,
                'ID_COMBINACION_PLANEAMIENTO no existe en MATRIZ_FUNCION_PERFIL_UNIDAD');
        END IF;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Diagnostico 024: referencias requeridas existentes y KEYCLOAK_ID disponible; no se ejecuto DML.');
END;
/

UNDEFINE ID_UNIDAD_PLANEAMIENTO
UNDEFINE ID_COMBINACION_PLANEAMIENTO
UNDEFINE KEYCLOAK_ID
UNDEFINE LOGIN
UNDEFINE CORREO_INSTITUCIONAL
UNDEFINE NOMBRE_COMPLETO
SET DEFINE OFF
